---
title: "Are Donors Really Responding? Analyzing the Impact of Global Restrictions on NGOs"
author:
- name: Suparna Chaudhry
  affiliation: Lewis and Clark College
  url: http://www.suparnachaudhry.com/
  email: schaudhry@lclark.edu
  orcid: 0000-0003-3506-7590
- name: Andrew Heiss
  affiliation: Georgia State University
  url: https://www.andrewheiss.com/
  email: aheiss@gsu.edu
  orcid: 0000-0002-3948-3914
format:
  html:
    code-tools: false
    toc: false
---

```{r}
#| label: setup
#| include: false

# yaml_metadata <- rmarkdown::yaml_front_matter(here::here("manuscript", "manuscript.qmd"))
# title <- yaml_metadata$title
# subtitle <- yaml_metadata$subtitle
# abstract <- yaml_metadata$abstract
```

## Abstract

The previous three decades have seen a proliferation of anti-NGO legislation throughout the world, resulting in increasingly restricted space for civil society organizations to provide services or engage in advocacy. This is worrisome for Western donors because they channel a large amount of foreign aid and democracy assistance funds through NGOs. How do donors respond to this legal crackdown on NGOs? We use original data on civil society restrictions across 148 countries from 1981–2013 to assess the impact of these restrictions on total flows of foreign aid, how aid is distributed, and which issues are funded. We find that additional anti-NGO legal barriers—in particular, barriers to advocacy—decrease the amount of foreign channeled to restrictive countries. Besides reducing the amount of aid, donors also redirect funds within restrictive countries, decreasing funds for politically sensitive causes in favor of tamer issues that are more compatible with the governments of those countries. Finally, donors—USAID in particular—channel more aid to domestic over foreign NGOs in order to assuage target country concerns about external interference in domestic politics. Our findings have worrying implications for donors in the foreign aid and democracy promotion community, whose projects may be unsustainable in the face of this legal crackdown.

## Code

All the raw code and data for this paper is available in a [GitHub repository](https://github.com/andrewheiss/verifiable-viper).
